# Generated by Django 4.0.4 on 2022-05-21 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_familia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoensistema',
            name='FingresoSist',
            field=models.DateField(default=datetime.datetime(2022, 5, 21, 18, 20, 6, 373398)),
        ),
    ]
